name: Prepare docker image
description: "Builds and pushed docker image to ghcr"
inputs:
  REGISTRY_HOST:
    description: "Registry Host"
    default: "dhcr.io"
  GITHUB_TOKEN:
    description: "Needed to authenticate in for operations with project/registry"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repo to $GITHUB_WORKSPACE
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      shell: bash
      run: docker login -u some ${{inputs.REGISTRY_HOST}} -p "${{inputs.GITHUB_TOKEN}}"

    - name: Build
      shell: bash
      run: docker build -t ${{inputs.REGISTRY_HOST}}/${GITHUB_REPOSITORY}:${GITHUB_SHA} .

    - name: Save
      shell: bash
      run: docker push ${{inputs.REGISTRY_HOST}}/${GITHUB_REPOSITORY}:${GITHUB_SHA}


