name: Set Tag
description: "Sets tag to repository"
inputs:
  GITHUB_TOKEN:
    description: "Needed to authenticate in for operations with project/registry"
    required: true
  TAG_BODY:
    description: "Main tag body that indicates what it is about"
    required: true
  ADD_DATE_POSTFIX:
    description: "Will be added date postfix to TAG_BODY after double '_'"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set tag
      shell: bash
      run: |
        if [ "x" = "x${{inputs.ADD_DATE_POSTFIX}}"  ];
        then 
          POSTFIX=""
        else
          POSTFIX=__$(date +"%Y-%m-%d__%H.%M.%S%z")
        fi
        
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{inputs.GITHUB_TOKEN}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs \
        -d "{\"ref\":\"refs/tags/${{inputs.TAG_BODY}}${POSTFIX}\",\"sha\":\"${GITHUB_SHA}\"}"



