name: Deploy at the same host
description: "Builds and pushed docker image to ghcr"
inputs:
  REGISTRY_HOST:
    description: "Registry Host"
    default: "dhcr.io"
  GITHUB_TOKEN:
    description: "Needed to authenticate in for operations with project/registry"
    required: true
  STAND_NAME:
    description: "Name of the stand"
    required: true
  FORCE_RECREATE:
    description: "Force recreate containers. Set '' to NOT recreate"
    default: '--force-recreate'
  CLEANUP_AFTER_START:
    description: "Runs 'docker system prune --all --force'. Set '' To omit this step"
    default: 'docker system prune --all --force'

runs:
  using: 'composite'
  steps:
    - name: Checkout repo to $GITHUB_WORKSPACE
      uses: actions/checkout@v3

    - name: Show ENVs
      shell: bash
      run: env

    - name: Login to Docker Hub
      shell: bash
      run: docker login -u some ${{inputs.REGISTRY_HOST}} -p "${{inputs.GITHUB_TOKEN}}"

    - name: Pull Image
      shell: bash
      run: docker pull ${{inputs.REGISTRY_HOST}}/${GITHUB_REPOSITORY}:${GITHUB_SHA}

    - name: Start container(s)
      shell: bash
      run: |
        project_name=$(echo "${GITHUB_REPOSITORY}" | sed 's/\//-/g')
        docker compose -p ${project_name} -f ${PWD}/docker-compose-${{inputs.STAND_NAME}}.yml up -d ${{inputs.FORCE_RECREATE}} --remove-orphans
        ${{inputs.CLEANUP_AFTER_START}}
